### ISSUE TITLE
[Request] Add: youporn.com (NSFW)

### ISSUE THREAD

**Issue by mister-sus** [Ultimate-Hosts-Blacklist/blacklist#10]
Hello there! 
I am a regular user. So I dont know much about programming, let alone configuring hosts file on my own.
I wanted to test the hosts file you provided, and it's a big blessing for privacy and to block sites that i dont want to be redirected/visit.

You, erm - missed this link : 

```
youporn.com
www.youporn.com
```

please add em :D

**Comment by smed79** [comment]
Hi, 
use the dns instead of the hosts file.
https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#dns-server

also scan your system for adware/malware
https://help.adblockplus.org/hc/en-us/articles/360062861653-What-is-adware-and-what-can-I-do-about-it-
