### ISSUE TITLE
Add abbaspc.net

### ISSUE THREAD

**Issue by wrt54g** [Ultimate-Hosts-Blacklist/blacklist#11]
Abbaspc.net is a WordPress site with redirects to malicious "crack" file downloads.
It has not been added to Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist yet

**Comment by smed79** [comment]
I suspect that you are clicking the [fake download button](https://imgur.com/bKJTgn6.png) which lead you to malicious sites.

**Comment by wrt54g** [comment]
@smed79 yes

**Comment by wrt54g** [comment]
@smed79 The download buttons all look the same. They go to the same crypto miner malware.

**Comment by smed79** [comment]
Added easylist https://github.com/easylist/easylist/pull/13299/commits/073810deb2c12e75506cc231f6b7ee5af6d47855
