### ISSUE TITLE
doi.org

### ISSUE THREAD

**Issue by Wiggum127** [Ultimate-Hosts-Blacklist/blacklist#13]
Don't see an obvious reason to block doi.org

**Comment by smed79** [comment]
`doi.org` is not blocked in **[blacklist](https://github.com/Ultimate-Hosts-Blacklist/blacklist/blob/master/domains.list)** and also [not blocked](https://www.diggui.com/#type=ANY&hostname=doi.org&nameserver=public&public=8.8.8.8&specify=88.198.70.38&clientsubnet=&tcp=def&transport=def&mapped=def&nssearch=def&trace=def&recurse=def&edns=def&dnssec=def&subnet=def&cookie=def&all=def&cmd=off&question=off&answer=def&authority=defditional=def&comments=off&stats=off&multiline=def&short=def&colorize=on) by UHB dns.

Please provide more more details and explain how to reproduce the issue.

**Comment by smed79** [comment]
`doi.org` is not blocked in **[blacklist](https://github.com/Ultimate-Hosts-Blacklist/blacklist/blob/master/domains.list)** and also [not blocked](https://www.diggui.com/#type=ANY&hostname=doi.org&nameserver=public&public=8.8.8.8&specify=88.198.70.38&clientsubnet=&tcp=def&transport=def&mapped=def&nssearch=def&trace=def&recurse=def&edns=def&dnssec=def&subnet=def&cookie=def&all=def&cmd=off&question=off&answer=def&authority=defditional=def&comments=off&stats=off&multiline=def&short=def&colorize=on) by UHB dns.

Please provide more more details and explain how to reproduce the issue.

**Comment by funilrys** [comment]
Closing. Please provide more details, as requested. 

Feel free to reopen.
