### ISSUE TITLE
sway.office.com

### ISSUE THREAD

**Issue by Wiggum127** [Ultimate-Hosts-Blacklist/blacklist#15]
No obvious reason to block sway.office.com

**Comment by smed79** [comment]
@Wiggum127 First look into **UHB** list using https://hosts.ubuntu101.co.za/app/contents/

`sway.office.com` is blocked in **Phishing.Database** 

see info https://github.com/Ultimate-Hosts-Blacklist/Phishing.Database/blob/master/info.json

then report to the upstream https://github.com/mitchellkrogza/Phishing.Database

@mitchellkrogza FYI.
