### ISSUE TITLE
Add "SS" website domains

### ISSUE THREAD

**Issue by ymhcanada** [Ultimate-Hosts-Blacklist/blacklist#16]
We would like to request the addition of two website domains associated with Sanctioned Suicide (SS) to the blocklist.

```
sanctioned-suicide.net
sanctioned-suicide.org
```

These domains have been identified as platforms that promote and discuss suicide methods, including those involving substances and gases, as mentioned in the [analysis conducted by the University of Padua](https://thesis.unipd.it/retrieve/3f2c4551-edf3-494f-9fc6-ff39821ac254/Sartori_Elisa.pdf). The analysis highlighted the presence of methods such as Hydrogen Sulfide, Sodium Azide, and Nembutal on the Sanctioned Suicide forum.

**Background Information:**

Sanctioned Suicide is an internet forum known for its open discussion and encouragement of suicide and suicide methods. The forum has garnered widespread scrutiny for its promotion of suicide.

Wikipedia
https://en.wikipedia.org/wiki/Sanctioned_Suicide

Letter from the Members of Congress
https://trahan.house.gov/uploadedfiles/doj_sanctioned_suicide_letter_final_dec21.pdf

The New York Times investigation
https://www.nytimes.com/interactive/2021/12/09/us/where-the-despairing-log-on.html

University of Padua analysis
https://thesis.unipd.it/retrieve/3f2c4551-edf3-494f-9fc6-ff39821ac254/Sartori_Elisa.pdf

Fix The 26
https://fixthe26.com/category/stop-sanctioned-suicide/

The presence of websites like Sanctioned Suicide, which openly discuss and encourage suicide methods, poses significant harm to online users. These platforms can have a detrimental impact on individuals who may already be vulnerable or struggling with mental health issues. By providing a space for the exchange of detailed information on suicide methods, these websites can potentially facilitate and normalize self-harm behaviors. This can further exacerbate feelings of hopelessness, isolation, and despair among individuals who are already contemplating suicide. Moreover, the exposure to such content can potentially trigger and influence vulnerable individuals, pushing them towards dangerous actions. It is crucial to take proactive measures to restrict access to these harmful websites in order to protect individuals and promote a safer online environment.

**Comment by Wiggum127** [comment]
Did some reading in the articles and the Wiki page. I've added the websites to my blocklist.

**Comment by ymhcanada** [comment]
@Wiggum127  Thank you very much! 
It means A LOT to us and the families we know. We thank you for your dedication and hard work in maintaining the list.
