### ISSUE TITLE
blacklist request - scam website(s) - sasnet.eu and sasnet.ovh

### ISSUE THREAD

**Issue by GarryStraitYT** [Ultimate-Hosts-Blacklist/blacklist#19]
Hello,
I'd first like to say thanks for the awesome project that's helped me regain control over my own Windows systems in the past.
However, there's a site going around that's selling and distributing malware-infected, pirated, and paid bootleg of Windows 11. This website is `sasnet.ovh`. This website has been reported to Microsoft on numerous occasions, and is cloned on/linked to the website `sasnet.eu`. I also have noticed that the websites have also distributed malware in a "feature pack" iso.

Thanks in advance for considering adding these websites to your project.

**Comment by smed79** [comment]
Hello,

Thanks for the report, but the site you are referring to does not fall under our blocking policy as the main focus of "UHB" is not dedicated to blocking warez sites or pirated software.

Thank you for understanding.

**Comment by GarryStraitYT** [comment]
Ah, I see.
nevertheless, thanks for creating the project!
