### ISSUE TITLE
Scam site not blocked 

### ISSUE THREAD

**Issue by Levander0** [Ultimate-Hosts-Blacklist/blacklist#20]
The scam domains: 
```
postislan.top
www.gym-sharkfinland.com
```

**Comment by Levander0** [comment]
www.gym-sharkfinland.com is a scam site as well

**Comment by Wiggum127** [comment]
both added to my blocklist

**Comment by smed79** [comment]
@Wiggum127 I deleted your post here by mistake. Sorry :pray:
