### ISSUE TITLE
Suggestion to add 

### ISSUE THREAD

**Issue by Wiggum127** [Ultimate-Hosts-Blacklist/blacklist#5]
https://my.forms.app/form/60db10ea7e6c303b0f172740
is a phishing form to trap people into providing their personal details using a fake GLS form.

**Comment by smed79** [comment]
Report abuse here https://forms.app/forms/contact-us

**Comment by Wiggum127** [comment]
Abuse reported. Form still accessible. Suggest to add it to blacklist anyhow.

**Comment by smed79** [comment]
Detected as malicious form and detected.

Closing ...
