### ISSUE TITLE
Add safkwesad.live

### ISSUE THREAD

**Issue by Wiggum127** [Ultimate-Hosts-Blacklist/blacklist#6]
Spam campaign launched with a link to this website, trying to scam people into providing personal details. Pretending to be an official governemental website.

**Comment by funilrys** [comment]
Server Down. Closing.

**Comment by funilrys** [comment]
@Wiggum127 Feel free to reopen.

**Comment by funilrys** [comment]
@Wiggum127 You now have write access to this repository. Feel free to contribute.

**Comment by funilrys** [comment]
*Contribution should be added into the `domains.list` file.

cc: @Wiggum127
