### ISSUE TITLE
Add adf.ly

### ISSUE THREAD

**Issue by wrt54g** [Ultimate-Hosts-Blacklist/blacklist#9]
adfly is a malicious URL shortner

**Comment by funilrys** [comment]
Please define malicious @wrt54g.

**Comment by wrt54g** [comment]
@funilrys Adfly sends push notifications redirecting to malware downloads and shows explicit ads on the shortened link.

**Comment by smed79** [comment]
Is blocked in [Ultimate.Hosts.Blacklist](https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist) and other various lists.
